### ISSUE TITLE
Blue Green Deployment missing

### ISSUE THREAD

**Issue by rohankasture** [airavata-courses/CookieArmy#102]

**Comment by jkumar10** [comment]
Hi, 

We have completed the Blue Green Deployment. We are in the process of updating the wiki which shall be ready within 30 min. 

Thanks.

**Comment by iarora93** [comment]
Hello,

You can begin with your testing.
A Wiki Page rough draft of Blue Green has been created which will soon be updated.
do let us know if any queries

**Comment by rohankasture** [comment]
I was searching if you have separate blue and green branches for microservices. I am not able to see through the Jenkins pipeline.

**Comment by iarora93** [comment]
We have not implemented that yet.
That is being done right now.

Blue Green has been done for TACC UI .
You can find the details in the Wiki

TACC Jenkins is http://129.114.104.159:8080
Same UI and password

You can begin testing on server level.
The services are running

ui                      replicated          1/1                 iarora/haproxy_green:latest

ui_blue                 replicated          1/1                 iarora/ui-tacc-blue:latest

ui_green                replicated          1/1                 iarora/ui-tacc-green:latest

Main UI service for tacc is ui.
Note it is currently pointing to iarora/haproxy_green:latest
To test it change the image to iarora/haproxy_blue:latest

Command details is in the Wiki page

Thanks & Regards,
Ishneet Singh Arora

**Comment by iarora93** [comment]
Hello ,

Jenkins job are created.
Currently ui service is using iarora/haproxy_green:latest

You can test for ui_tacc_blue job once it is up and running (can check using http://129.114.104.73:8300/)

You switch the ui to point to blue image

docker service update --update-order start-first --image iarora/haproxy_blue ui

before running this please run on a different machine
--> docker run --rm bretfisher/httping -i .1 -G -s -Y http://129.114.104.73:8100/ you will come to know if there is any package loss

Thanks & Regards,
Ishneet Singh Arora

From: Arora, Ishneet Singh Gurdeep Singh<mailto:iarora@iu.edu>
Sent: 24 April 2019 22:13
To: airavata-courses/CookieArmy<mailto:reply@reply.github.com>; airavata-courses/CookieArmy<mailto:CookieArmy@noreply.github.com>
Cc: Comment<mailto:comment@noreply.github.com>
Subject: RE: [airavata-courses/CookieArmy] Blue Green Deployment missing (#102)

We have not implemented that yet.
That is being done right now.

Blue Green has been done for TACC UI .
You can find the details in the Wiki

TACC Jenkins is http://129.114.104.159:8080
Same UI and password

You can begin testing on server level.
The services are running

ui                      replicated          1/1                 iarora/haproxy_green:latest

ui_blue                 replicated          1/1                 iarora/ui-tacc-blue:latest

ui_green                replicated          1/1                 iarora/ui-tacc-green:latest

Main UI service for tacc is ui.
Note it is currently pointing to iarora/haproxy_green:latest
To test it change the image to iarora/haproxy_blue:latest

Command details is in the Wiki page

Thanks & Regards,
Ishneet Singh Arora

**Comment by rohankasture** [comment]
Cool. This looks good.
