### ISSUE TITLE
Allows users to login without any credentials

### ISSUE THREAD

**Issue by vrishalibhor** [airavata-courses/CookieArmy#114]
![image](https://user-images.githubusercontent.com/46794230/56781110-edea3e00-67af-11e9-80d8-71ef04440593.png)

I am able to log in to the application without providing any credentials. Please let me know if I am missing anything.

**Comment by ATarfe** [comment]
Hi Team,

I am facing the same issue. Please look into it.

**Comment by gattur** [comment]
Thanks for finding the bug.
Issue has been fixed. Could you please check http://149.165.170.196:8100

**Comment by vrishalibhor** [comment]
Fixed
