### ISSUE TITLE
Hard coded requested rides.

### ISSUE THREAD

**Issue by ATarfe** [airavata-courses/CookieArmy#115]
Whenever I am redirected to the landing page, there are some of the rides already requested.

**Comment by gattur** [comment]
Issue has been fixed. Could you please check http://149.165.170.196:8450

**Comment by ATarfe** [comment]
I am not able to access the link provided.

**Comment by gattur** [comment]
Sorry wrong port number, could you check on this http://149.165.170.196:8100/

**Comment by ATarfe** [comment]
The issue still persists.

**Comment by ATarfe** [comment]
![Screenshot_20190426-205713__01](https://user-images.githubusercontent.com/29509353/56842682-00bf4a00-6866-11e9-8a4d-c21e892659f6.jpg)

**Comment by iarora93** [comment]
Hi Ameya,

What do you mean by hard coded.

This is the snippet from the DB

![image](https://user-images.githubusercontent.com/46791010/56843714-847f3380-6872-11e9-9c9c-a3a9c317bc6d.png)

See the screenshot if the GUI 
![image](https://user-images.githubusercontent.com/46791010/56843721-c9a36580-6872-11e9-8f13-5e6a2b7a057d.png)

**Comment by iarora93** [comment]
We have added 2 test cases please test once 
I guess you have not logged in

**Comment by iarora93** [comment]
Once you have successfully tested we will remove the test case which has been added

**Comment by ATarfe** [comment]
Hi team,
At first, there were some already requested rides in my account. But, it seems to be fixed now.

**Comment by iarora93** [comment]
Thank you  for the confirmation
