### ISSUE TITLE
OpenID connect missing

### ISSUE THREAD

**Issue by ATarfe** [airavata-courses/CookieArmy#117]
Login using OAuth feature was missing.

**Comment by iarora93** [comment]
Hi,

OAuth has already been integrated.
You can check it in login tab and not in new user tab

http://149.165.170.196:8100/rides/tabs/rides-available

**Comment by ATarfe** [comment]
Earlier, I couldn't see any Login using Google. It works fine now though.

**Comment by iarora93** [comment]
Thank you for the confirmation
