### ISSUE TITLE
Peer review Summary

### ISSUE THREAD

**Issue by ATarfe** [airavata-courses/CookieArmy#118]
Hi Team,

Good job overall. The UI is minimal which is good. I have raised certain issues which I came across while reviewing. These are as follows:

- Hard coded requested rides. #115 
- Blank 'About' page. #116 
- OpenID Connect missing. #117 
- Sign up redirect not working. #113 

Thanks and regards,
Amey Avinash Tarfe

**Comment by gattur** [comment]
Hi Amey,
Thanks for the feedback.
could you please check now on http://149.165.170.196:8100/

**Comment by gattur** [comment]
blank about page will be updated

**Comment by gattur** [comment]
about page has been updated.

**Comment by ATarfe** [comment]
Thanks for addressing the issue.

**Comment by jkumar10** [comment]
All the issues that have been mentioned has been addressed and completed. Please check and let us know.
