### ISSUE TITLE
Assignment 4 review 

### ISSUE THREAD

**Issue by vrishalibhor** [airavata-courses/CookieArmy#121]
Hi Team,

Great work on the project. I, however, feel that the UI of the application could be made more attractive. Other than that,  I have the following issues:

Blank 'About' page. #116 
Redirect to sign up form does not work #113 
Allows users to login without any credentials #114 
Able to book ride even without logging in #122

Also, it would have been better if blue-green deployment was done on all the microservices as against only with the UI.

Thanks,
Vrishali

**Comment by gattur** [comment]
Thanks for the feedback.
 
Regarding the UI can be made attractive, our application has been designed for mobile applications. as we can see from the screenshot of the the issue you have raised https://github.com/airavata-courses/CookieArmy/issues/116, you are viewing in the normal mode. could you please view in mobile view by right click and select inspect. I think we have not added this point in milestone 4 wiki. we will update wiki.
other  issues have been fixed, could you please check on http://149.165.170.196:8100/
