### ISSUE TITLE
Able to book ride even without logging in

### ISSUE THREAD

**Issue by vrishalibhor** [airavata-courses/CookieArmy#122]
I am able to book a ride even without logging in. Please let me know if I'm misunderstanding the functionality

**Comment by iarora93** [comment]
Hello Vrishali,

Could you please test once again

**Comment by gattur** [comment]
Could you please check at http://149.165.170.196:8450

**Comment by gattur** [comment]
Could you please check at http://149.165.170.196:8100

**Comment by vrishalibhor** [comment]
Works fine now.
