### ISSUE TITLE
Update document and query

### ISSUE THREAD

**Issue by sairohithA007** [airavata-courses/CookieArmy#17]
Environment: MacOS Mojave (Version: 10.14.3)
a. Specifying which branch to clone is missed. 
b. In offering.offering_a_ride table and in offering1.offering_a_ride , the column “Contact Details” has space. Because of the space, the query did not execute on MySQLworkbench. 
c. For Email Service queries 
       i. There is an ambiguity with schema names. I have assumed that the second schema’s name as 'offering1' and ran the queries for email service 
d. SGA-mysql-final: 
      i. Update ‘Contact Details’ to ‘ContactDetails’ in the code in order to run the application with the change in the column name "ContactDetails"
     ii. Details to specify the build type(Gradle, maven etc..,).
e. UI: Additionally, I ran the below command to run the application 
      i. npm install -g cordova ionic

**Comment by iarora93** [comment]
Hi Sai,

I have updated the package so that Queries can be executed directly.
Also, the release instructions have been updated.
Do let us know if any further changes are required

**Comment by sairohithA007** [comment]
The document is more clear now when compared to the previous once. This issue can be closed.
