### ISSUE TITLE
Issues in Authorization Service

### ISSUE THREAD

**Issue by sairohithA007** [airavata-courses/CookieArmy#18]
Environment: macOS Mojave (Version: 10.14.3)
a. As password is sensitive information, need to encrypt the password before storing in the sqlite db.
b. Need to move the requirements.txt from project’s root directory to authorization_microservice directory so that the python related components will be in same directory.

**Comment by jkumar10** [comment]
I have moved the requirements.txt inside the authorization_microservice as you suggested. I have also improved the python flask wiki more easy to read and understand.

**Comment by jkumar10** [comment]
Hi, 
I have added password encryption using sha 256 and have verified the functionality, 

Thanks.

**Comment by sairohithA007** [comment]
The fix looks good.
