### ISSUE TITLE
CORS policy error in during login (Windows)

### ISSUE THREAD

**Issue by bhushanmalgaonkar** [airavata-courses/CookieArmy#19]
![image](https://user-images.githubusercontent.com/6957870/52390181-18581500-2a65-11e9-83f9-09aabd77fccf.png)

**Comment by jkumar10** [comment]
Normally CORS error should not come because I already added a CORS dependency that should handle that error. Try to re-inistall CORS inside the virtual environment by pip install flask-cors and let me know.

**Comment by jkumar10** [comment]
Hi, 
I have re-verified the CORS issue you are facing, checked and tested it again . Cors dependency need to be installed inside the virtual environment as well.  
Thanks. :)

**Comment by bhushanmalgaonkar** [comment]
The login is working correctly now.!

**Comment by jkumar10** [comment]
okay thanks!
