### ISSUE TITLE
DB deployment steps need improvement - alakh-pr1

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/CookieArmy#22]
1. Please include the link to download MySQL db.
2. Include steps on how to start the DB and the steps to include environment variables.
3. Also, the first step in your wiki, you should include git clone and git checkout command.
4. For all the other modules which needed to be installed please include appropriate links for windows and mac platforms.

**Comment by iarora93** [comment]
Hello Alakh,

Release instructions have been updated,
You can find the instructions in the development Branch.

Do let us know if any other changes are required.

Also please git clone the development branch once again

**Comment by alakhsingh** [comment]
Hi @iarora93 the link you have attached for mysql installation instructions doesn't say how to fire up mysql or set the path variables.
Please update the wiki for the same. 
refer https://stackoverflow.com/questions/32858216/error-1045-28000-access-denied-for-user-rootlocalhost-using-password-n

**Comment by iarora93** [comment]
Hello,

You can go to the path where MySQL is installed, go to bin folder and  run ./mysql -u root
If there is some issue please check if the instance is running or not.
 

The instructions were mentioned on the same page about which is given in Wiki
https://dev.mysql.com/doc/refman/5.5/en/osx-installation-launchd.html
https://dev.mysql.com/doc/refman/5.5/en/osx-installation-prefpane.html

Still, if you face an issue do let me know
