### ISSUE TITLE
[Authorization Service] - Deployment issues

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/CookieArmy#23]
After cloning the repo, please specify the branch name on the top of your wiki.
It also seems that ‘setprojectdir .’ and 'mkvirtualenv [virtual environment name]' command doesn’t work in my pc (Mac).

Below are the modules which did not install in my system
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.

Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by jkumar10** [comment]
Hi Alakh, 
You can use the development branch to clone the repo as it is written in the step 1 of wiki. 
Run command "pip install virtualenv virtualenvwrapper" for mac and then try running those commands.
Although it is preferred to create a virtual environment, it is not required. The modules which you referred not installed are not required. So try running the application without them and let me know.

**Comment by alakhsingh** [comment]
Hi,
I don't think the last steps work on mac environment, at least it didn't work for me. I found a solution for it here https://stackoverflow.com/questions/31252791/flask-importerror-no-module-named-flask
Can you please test this and if it works update your wiki for the same.

Also,
This is the error I get when I run "flask run --port=7998"
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by jkumar10** [comment]
Hi Alakh, can you please try this and let me know: 
On mac:
1. To install virtual environment
pip install virtualenv

2. After it gets installed go the project folder and run:
virtualenv [name of the environment] e.g. virtualenv myflaskenv

3. To activate on Mac try this:
source myflaskenv/bin/activate

4. Inside it you can run requirements.txt

Thanks.

**Comment by alakhsingh** [comment]
Hi @jkumar10 ,
The last steps for running the microservice do not work for mac. Here is the solution I found. 
https://stackoverflow.com/questions/51119495/cannot-setup-flask-how-to-setup-environment-variable-in-windows
If you think this works, please update the wiki for the same and confirm then I will close this issue.
