### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by bhushanmalgaonkar** [airavata-courses/CookieArmy#25]
**1. Error handling can be improved**

Nodejs provides easy to use callback/promise mechanisms for error handling. 

e.g. while starting server you can use following code so that you know exactly what went wrong when some error occurs. `app.listen(3000).on('error', console.log);`

**2. Sending http statuses**

Sending appropriate statuses makes debugging a lot easier in such projects, where services talk to each other in a chain structure.

e.g. if the sending a mail fails, you can send 500 to let the consumer service know that something went wrong on the server side. Instead, if the email was null, you can send 400 stating that it was a bad request and nothing wrong with the server, so consumer can take action accordingly.

In Nodejs we can set status using `res.status(200).send(message_to_send);`. 

**3. Null checks**

You should use plenty of these to make your system as robust as possible.

e.g. Consider email service. Since each service is independent, you cannot guarantee that each consumer of email service will send correct parameters in the request. It's the service's responsibility to validate all the input parameters. If anything is missing, you can simply send 400. With this implemented adding new services to the systems is lot easier since you get immediate feedback when you miss some parameters.

**4. I think the else block in `transporter.sendMail` should have parentheses around it.**

Also, when some error occurs and you are not handling it, pass it to the consumer using http status.

**Comment by jkumar10** [comment]
Thanks Bhushan for pointing out the improvements that we can do in our application. We will definitely take care of these above-mentioned points in our project and will improve our application.
