### ISSUE TITLE
[Hybrid Mobile Application] service failed to deploy

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/CookieArmy#26]
Build is failing. 
<img width="1434" alt="screenshot 2019-02-10 at 12 08 14 am" src="https://user-images.githubusercontent.com/20154848/52529869-3f625100-2cc8-11e9-9fe0-8793beefaeaa.png">

**Comment by gattur** [comment]
Hi Alakh,

Could you please try
npm rebuild node-sass

https://github.com/webpack-contrib/sass-loader/issues/530

**Comment by alakhsingh** [comment]
Hi,
That solution didn't work, although I tried https://stackoverflow.com/questions/48147896/error-in-cannot-find-module-node-sass which solved the problem.

**Comment by gattur** [comment]
Hi Alakh,

Thanks for the update.
Could you please post the command that worked for you, for future reference.

Thanks,
Gattu

**Comment by alakhsingh** [comment]
Hi @gattur, The post I linked in my last comment has the command.

**Comment by gattur** [comment]
HI @alakhsingh 
I could see that in the post you have added
https://stackoverflow.com/questions/48147896/error-in-cannot-find-module-node-sass
this was the command used "npm rebuild node-sass". But you mentioned to have used another command that worked for you. 
As, we have not tested on mac. It would be really helpful, if you can post the exact command that worked for you.

Thanks,
Gattu

**Comment by alakhsingh** [comment]
Hi @gattur ,
sudo npm install --save-dev  --unsafe-perm node-sass

Thanks,
Alakh

**Comment by gattur** [comment]
Thanks Alakh for the update
