### ISSUE TITLE
Peer Review Milestone 1

### ISSUE THREAD

**Issue by bhushanmalgaonkar** [airavata-courses/CookieArmy#29]
Good job guys!

The documentation is much better now. Deploying services was very easy. The UI is clean and easy to use.

Only issues I faced were CORS policy issue at login #19 and issues with earlier documentation #17 (raised by @sairohithA007). Apart from that the system is working correctly.

For the code, I have few suggestions which I have mentioned in #25

Thanks,
Bhushan

**Comment by jkumar10** [comment]
Thanks Bhushan for peer reviewing our project. We have addressed and fixed most of the issues and we will further improve this application in the next phase. We appreciate your time and effort in peer reviewing. :)
