### ISSUE TITLE
JDBC database connectivity issues

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/CookieArmy#30]
Hi,
As from wiki, I created the mysql db, and added the details in properties file. I get an error 
 Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)] with root cause

**Comment by iarora93** [comment]
Hello,

Have you updated the below mentioned credentials in application.properties (SGA-mysql-Final folder)
spring.datasource.username=root
spring.datasource.password=
