### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/CookieArmy#35]
Hey team,

I just started with the code review. Will update my progress/issues here.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hello Team,

Please update the wiki as soon as possible with steps to checkout and run your project in linux environment.
I am unable to follow steps to run virtual env for linux.

**Comment by iarora93** [comment]
Hi Nawaz,

We have created separate instructions for Linux platform.

Link for the same is https://github.com/airavata-courses/CookieArmy/wiki/Release-Instructions-Linux

Thanks
CookieArmy

**Comment by nawazkh** [comment]
Hey Team,

I see a lot of effort has been put in writing the documentation of your project. Kudos for that! 

I am still facing some issues with the installation, Please follow up with me on Slack. 

Regards,
Nawaz

**Comment by nawazkh** [comment]
Hey Team,
I followed all the steps mentioned on the Linux release date. 

<img width="1268" alt="screen shot 2019-02-22 at 12 18 11 am" src="https://user-images.githubusercontent.com/25679594/53221467-7543f580-3637-11e9-9062-de0756d34067.png">
This is error I got on running the final step.

Can you help me resolve this?

**Comment by gattur** [comment]
Hello Nawaz,

Could you try 
sudo npm install --save-dev --unsafe-perm node-sass

**Comment by nawazkh** [comment]
Sure, which branch do I run the above command?

Edit 1: assuming to run it in Hybrid Mobile App

Edit 2: It doesn't help, facing the same issue.

**Comment by iarora93** [comment]
This issue was faced earlier and was solved using the steps mentioned in the issue attached.
please run the command on the hybrid mobile app.

https://github.com/airavata-courses/CookieArmy/issues/26

**Comment by nawazkh** [comment]
Do mention this page in your wiki on installing mysql https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-18-04

**Comment by nawazkh** [comment]
Hey Team, 

Great job on the project! It is working good and I could login and check for available rides.

Here is my summary:
1. When I book a ride, should I be seeing it in the requested ride as well? I could not see it in this demo.
2. Rides posted page is blank even though I had created new rides. Is this something expected? 

Related to project:
1. Please come up with test cases to test your functionality. It is highly recommended as we progress in the project.
2. Please streamline your documentation.

Apart from that, Kudos for the effort! Its a great project! 

Keep up the good work!

Thanks,
Nawaz

**Comment by gattur** [comment]
Hi Nawaz,
1. we have not added requested ride in Project 1, would be added in future releases.
2. Rides Posted page has not been added yet.

Related to project.
1. We did not know that we have to add test cases in documentation for each micro service. we would update to it.

**Comment by nawazkh** [comment]
Oh no, you need not mention test cases in the documentation. 

Suggestion 1 in "related to projects" was for java service. On building the service, it built the jar successfully without checking if there was a connection with the DB. 
If there was a test case to test the connection at the time of building the jar, we would not face run time SQLConnectionException. 
Including a test case to check it would definitely help you in the future builds.
