### ISSUE TITLE
[PEER REVIEW] Jenkins pipeline - DBService

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/CookieArmy#48]
Pushed a dummy commit to the development branch (in DB Service). I do not see build trigger in Jenkins.

Please let me know if I am missing something here.

Thanks,
Roja

**Comment by jkumar10** [comment]
Hi Roja, 
I can see a build triggered in our Jenkins by the test commit you made. Can you please check again if you are able to see the commit in "Last Success". It shows like build triggered 6 min 5 sec ago.

**Comment by rojaraman** [comment]
I made a commit 2 mins ago, but jenkins still shows 7mins ago.

Not sure what is the behaviour like. If this is normal, then you can ignore the issue
![cookiearmy3](https://user-images.githubusercontent.com/7594406/53702053-11f15a80-3dd1-11e9-973e-5d29e076b925.JPG)
![cookiearmy4](https://user-images.githubusercontent.com/7594406/53702054-11f15a80-3dd1-11e9-83a9-6057b3224297.JPG)

**Comment by rojaraman** [comment]
Also, Now I see Authentication service failed due to some reason

http://149.165.171.27:8080/job/authentication/168/console

**Comment by iarora93** [comment]
Hello Roja,

We have made some changes now.
Have tested it and it seems to be working fine.

Could you please retry?

Thanks,
CookieArmy

**Comment by rojaraman** [comment]
Build triggered and successfully built the jobs. 
Closing issue.
