### ISSUE TITLE
Peer Review Milestone 2 

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/CookieArmy#52]
Hi Team,

Overall, the project looks good.
Jenkins and service discovery works fine.
I have raised issue #46 #48 #47 (Pending) as a part of this peer review.

Thanks,
Roja Raman

**Comment by gattur** [comment]
Hi,
Thanks for the feedback, we are working on adding pop ups for smooth functionality. 
Lot of white space is due to not using using in mobile screen size, as we are developing for mobile applications.  which can be done by inspect and choosing a mobile screen.

Thanks,
Gattu
