### ISSUE TITLE
Peer Review  Summary Milestone #2

### ISSUE THREAD

**Issue by PulkitMathur** [airavata-courses/CookieArmy#55]
Peer Review Summary:

1.	Napkin and Architecture Diagram helps to get a clear idea of what the application is about.
2.	Easily able to login into Jenkins and Consul.
3.	To test the entire CI/CD, a different pipeline could have been made which triggers building and deployment for all the microservices.
4.	Wiki should contain the use cases for the application. For example, what should a user expect when he is unable to locate a car, or the application is not able to detect user’s location.
5.	Email Microservice return nothing when pinged directly on http://149.165.170.87:3000/ via browser.
6.	Login/Sign up should be before I am able to see any rides.
7.	UI and Functionality
a.	No option to login or register. It directly shows me all the available rides
b.	A new page open when clicked on “Request Rides” but with no data/information.
c.	A google map could be displayed on the “Available Rides” page below the list of rides which shows driver’s ETA and route map and other things like Lyft or Uber application when booking a ride.
d.	Once I login, the UI should show somewhere that I logged in. User details page is blank. No back button on “details” page. At least user should be able to save card details in order to pay for booked ride.
e.	No action on clicking “BOOK” button on any ride.
f.	After sign up, I should be redirected to sign in page and after sign in, I should be directed to the page where I am booking the ride I selected previously.
g.	While adding ride, not able to enter date in MM/DD/YYYY format. Either a date picker could be provided, or it should throw error if I am not entering date in correct format. Another option would be to show date format below Date column after user clicks on the date row.
h.	Dollar symbol should be appended before amount. Just as a feature improvement, currency should be automatically selected based on start and end destination country.
i.	The about page for the application is blank.
j.	No error or message provided if password or username is wrong.
k.	Overall the UI could much more interactive and user friendly.

**Comment by iarora93** [comment]
Thanks Pulkit.

All the UI changes suggested have been implemented other than google map integration.
This is not a cab application.
This is actually a car pool  application so there is no live tracking like in a case of taxi
