### ISSUE TITLE
PR MS2: CI/CD Jenkins is not reading latest commit

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/CookieArmy#57]
CookieArmy/DbService/src/main/java/com/example/demo/SgaMysqlFinalApplication.java

Modified the file and added a compile error but none of the builds faile.

**Comment by iarora93** [comment]
Hello,

On checking the commit was done 12 mins back.
On checking Jenkins last run was 10 mins back.

I guess it was due to the commit only.

Thanks,
CookieArmy

**Comment by harishmaruthi** [comment]
There was a compilation error with the code. The build was triggered but I did not see any failures. Please note this and close the issue if the issue persists

**Comment by iarora93** [comment]
Hello Harish,

We have provided the fix for the DB Service.
Now in Jenkins, it fails if the build fails.

Thank you for  checking!

**Comment by harishmaruthi** [comment]
Could you all please share the fix details for future reference on this thread, or a commit URL can be linked if any code changes are checked in.
