### ISSUE TITLE
PR MS2: UI- "Book" functionality

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/CookieArmy#58]
I tried clicking "book". But I was unable to book the ride.

**Comment by iarora93** [comment]
We have not added a Pop-Up button yet which shows the booking confirmation.
If you have provided the right email address, then you should have received a mail.

**Comment by harishmaruthi** [comment]
That seems to be nice. Then please change this task as a backlog item or an
enhancement appropriately. Or we can close this issue if the idea was not
in the scope of the requirements for these milestones.

Thanks ,
Harish.
