### ISSUE TITLE
PR MS2: Consul to have all the services

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/CookieArmy#61]
Service discovery to be extended to all the services

**Comment by iarora93** [comment]
Hello Harish,

We have added all the services to Consul
You could check the same on http://149.165.171.27:8500/ui/us-central/services

**Comment by harishmaruthi** [comment]
Oh nice...I have validated it. Please do close the issue if there isn't anything remaining for this task.

Also, Please do add the root cause of the issue and the fix you provided. Helps us understand more and learn about the issue and other teams can avoid such issues.

Thanks,
Harish.

**Comment by iarora93** [comment]
We have just installed consul on each server for each server and configured them together like how we had done it for DB Service

**Comment by harishmaruthi** [comment]
Verified. 4 of the services are discovered and registered on to Consul.
