### ISSUE TITLE
Email Service 1 Down

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/CookieArmy#79]
Hey,
The email service 1  is down: http://149.165.170.87:3000/
Docker Swarm should have handled that, but it didn't.

**Comment by iarora93** [comment]
Hi Chirag,

We were facing some issue with the node and have deleted the node.
Right now we just have 2 servers for Email Service.


149.165.157.145 | Email 2 | http://149.165.157.145:3000/
149.165.169.83 | Email 3 | http://149.165.169.83:3000/

We will update the Wiki page shortly.

Thanks,
Team CookieArmy

**Comment by iarora93** [comment]
We have only 2 Servers
