### ISSUE TITLE
[BUG] No Error checking while adding rides

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/CookieArmy#83]
The application accepted my data which was incorrect as attached below.
The adding rides page should have a date picker and time picker to prevent wrong information being added to the system. 
<img width="517" alt="Screen Shot 2019-04-03 at 11 54 25 AM" src="https://user-images.githubusercontent.com/4441071/55493729-80f7e400-5607-11e9-901a-ac23518fed84.png">

**Comment by jkumar10** [comment]
Thanks for the suggestion, we have implemented it in assignment 4.
