### ISSUE TITLE
Assignment 3 peer review 

### ISSUE THREAD

**Issue by BBaggines** [airavata-courses/CookieArmy#89]

**Comment by BBaggines** [comment]
Hello Team,
I went through the code and wiki to understand the project. The architecture looks fine. I tried using the app using the link given in the wiki. I was unable to sign up/sign in. There seems to be something broken in the code there. Lmk when this is fixed and I can test again.
You can also try to increase the number replicas for microservice and check the change in throughput and error rate. 

Regards,
Shradha

**Comment by iarora93** [comment]
Hello Shradha,

Could you please check now.
It is working for us when we checked.
Also please use inspect mode since it is a mobile application

Let us know if you facing any issues

Regards,

Ishneet Singh
