### ISSUE TITLE
Architecture Diagram for Assignment 3

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/CookieArmy#90]
The architecture diagram for assignment 3 including docker, Docker swarm is not updated yet. Can you please update the diagram

**Comment by jkumar10** [comment]
Hi Chirag, 

It is updated, https://github.com/airavata-courses/CookieArmy/wiki/Project-3-release-instructions
Cluster is the docker swarm cluster.

**Comment by psethu** [comment]
Agree with jkumar

**Comment by Chirag-Galani** [comment]
Ok. Sorry, I didn't know that.
