### ISSUE TITLE
[DOCKER] Service docker containers do not share common slave instances

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/CookieArmy#91]
After having a conversation with @iarora93, I have a decent understanding of the Docker-Swam cluster orchestration process. The idea of creating multiple masters ensuring maximum availability is a brilliant one since the system is more fault tolerant in case the master node fails.
But, the containers for each service could have been deployed on the same server instances as slaves, instead of independent server specific instance. They could have shared the slave IP addresses and could be hosted on different ports on the slave machine.

**Comment by iarora93** [comment]
Hello Chirag,

Suggested changes were implemented.

Now we have a single docker swarm cluster for each data center
