### ISSUE TITLE
Please update project wiki for Milestone 4

### ISSUE THREAD

**Issue by rohankasture** [airavata-courses/CookieArmy#96]

**Comment by jkumar10** [comment]
Hello,

I assume Jenkins credentials and load balancing test has already been provided to you by Ishneet. You can review that. Meanwhile, final testing for Blue-Green is currently going on and we are currently in the process of creating wiki pages for the same.

**Comment by rohankasture** [comment]
Yes. I received that mail but I am still waiting for the updated wiki as it will be better if you give me access to kubernetes master to see the deployments
