### ISSUE TITLE
Wiki and Jenkins Credentials

### ISSUE THREAD

**Issue by vrishalibhor** [airavata-courses/CookieArmy#97]
Hello Team,

Please update wiki and share Jenkins Credentials

**Comment by jkumar10** [comment]
Hello,

I assume Jenkins credentials and load balancing test has already been provided to you by Ishneet. You can check that. Final testing for Blue-Green is currently going on and we are currently in the process of creating wiki pages for the same.

**Comment by iarora93** [comment]
Hello,

You can begin with your testing.
A rough draft of Blue Green has been created which will soon be updated.
do let us know if any queries
Also please provide your us with your public key so that you can begin with your testing
